record entity-summary {
    kind: u8,
    danger: u8,
    x: u32,
    y: u32,
}

record entity {
    kind: u8,
    
    x: u32,
    y: u32,

    energy: u16,
    shield: u8,
    blasters: u8,
    thrusters: u8,
    harvesters: u8,
}

pack: func(e: entity-summary) -> list<u8>
step: func(e: entity, cell: list<u8>) -> u8
decodecmd: func(m: u8) -> string