type plan = u64

record entity-summary {
    kind: u8,
    danger: u8,
    x: u32,
    y: u32,
}

record entity {
    kind: u8,
    
    x: u32,
    y: u32,

    energy: u16,
    shield: u8,
    blasters: u8,
    thrusters: u8,
    harvesters: u8,
}

pack: func(e: entity-summary) -> list<u8>
decodeplan: func(p: plan) -> string
applyplan: func(e: entity, p: plan) -> list<entity>

// export agent strategies here! please prefix them with "strategy-"
strategy-flee: func(e: entity, last-plan: plan, system: list<u8>) -> plan
strategy-battle: func(e: entity, last-plan: plan, system: list<u8>) -> plan
strategy-blank: func(e: entity, last-plan: plan, system: list<u8>) -> plan

// the default strategy has to be named "strategy-default"
strategy-default: func(e: entity, last-plan: plan, system: list<u8>) -> plan